[
    {
        year: 1999,
        month: 6,
        day: 4,
        gender: 'male',
        controlNumber: '9670',
    },
    {
        year: 1988,
        month: 7,
        day: 5,
        gender: 'female',
        controlNumber: '1467',
    },
    {
        year: 2001,
        month: 7,
        day: 1,
        gender: 'female',
        controlNumber: '6299',
    },
    {
        year: 1971,
        month: 5,
        day: 22,
        gender: 'female',
        controlNumber: '1799',
    },
    {
        year: 1973,
        month: 7,
        day: 6,
        gender: 'female',
        controlNumber: '2504',
    },
    {
        year: 1981,
        month: 2,
        day: 7,
        gender: 'male',
        controlNumber: '9271',
    },
    {
        year: 2001,
        month: 9,
        day: 9,
        gender: 'male',
        controlNumber: '6295',
    },
    {
        year: 1967,
        month: 10,
        day: 4,
        gender: 'male',
        controlNumber: '2229',
    },
    {
        year: 1975,
        month: 1,
        day: 5,
        gender: 'male',
        controlNumber: '5056',
    },
    {
        year: 1984,
        month: 6,
        day: 17,
        gender: 'female',
        controlNumber: '8489',
    },
];
